_target_: src.models.simple_model.SimpleModel
datamodule: ${datamodule}

optimizer_partial:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

net:
  _target_: torchvision.models.resnet18
